database {
    profile = "slick.jdbc.PostgresProfile$"
    db {
      url = "jdbc:postgresql://localhost:55432/postgres"
      user = "postgres"
      password = "postgres"
      driver = "org.postgresql.Driver"
      numThreads = 10
      maxConnections = 10
    }
}